# Generated by Django 5.1.2 on 2024-10-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='qasim1122@gmail.com', max_length=254, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
