# Generated by Django 5.1.2 on 2024-10-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pswd',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrName',
            field=models.CharField(max_length=30),
        ),
    ]
